# Generated by Django 3.0.3 on 2020-07-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200712_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completeby',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
